<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WarbandStudio.Core\WarbandStudio.Core.csproj" />
    <ProjectReference Include="..\WarbandStudio.Rpfm\WarbandStudio.Rpfm.csproj" />
    <ProjectReference Include="..\WarbandStudio.Packfile\WarbandStudio.Packfile.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
