<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WarbandStudio.Core\WarbandStudio.Core.csproj" />
    <ProjectReference Include="..\WarbandStudio.Pack\WarbandStudio.Pack.csproj" />
    <ProjectReference Include="..\WarbandStudio.Rpfm\WarbandStudio.Rpfm.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
